openapi: 3.0.0

info:
  title: GrFN spec
  description: Grounded Function Network (GrFN) schema specification
  contact:
    name: Clayton T. Morrison
    email: claytonm@email.arizona.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 2.1.0

paths: {}

components:

  schemas:

    grfn:
      title: <grfn>
      description: >
        Top-level structure.
        A <grfn_def> corresponds to a namespace.
      required:
        - uid
        - date_created
        - functions
        - variables
        - edges
        - containers
      properties:
        uid:
          type: string
          description: unique identifier
        date_created:
          type: string
          format: date-time
          description: >
            Date and time that current GrFN was generated.
        variables:
          type: array
          items:
            $ref: '#/components/schemas/variable'
        functions:
          type: array
          items:
            $ref: '#/components/schemas/function'
        edges:
          type: array
          items:
            $ref: '#/components/schemas/edge'
        subgraphs:
          type: array
          items:
            $ref: '#/components/schemas/subgraph'
        # metadata
        metadata:
          description: Metadata associated with \<grfn>.
          type: array
          items:
            $ref: '#/components/schemas/metadata'

    edge:
      title: <edge>
      description: GrFN edge
      required:
      - in
      - function
      - out
      properties:
        in:
          type: array
          items:
            $ref: '#/components/schemas/variable'
        function:
          $ref: '#/components/schemas/function'
        out:
          type: array
          items:
            $ref: '#/components/schemas/variable'

    variable:
      title: <variable>
      description: A representation of a variable extracted from source code
      required:
        - identifier
        - uid
        - reference
      properties:
        identifier:
          type: string
          description: (name) variable basename and index extracted from source code
        uid:
          type: string
          description: variable unique identifier
        type:
          description: float32, float64, integer, string, boolean
          type: string
        kind:
          description: (measurement_scale) The measurement scale of this data-type binary/categorical/discrete/continuous
          type: string
        domain:
          description: >
            Expression of the possible values data can take, as interval
            \"(and (> v -infty) (< v infty))\"
          type: string
        reference:
          type: string
          description: grounding reference to scientific variable ontology
        # metadata
        metadata:
          description: Metadata associated with \<variable>.
          type: array
          items:
            $ref: '#/components/schemas/metadata'

    function:
      title: <function>
      description: A representation of a functional computation extracted from source code
      required:
        - uid
        - type
        - reference
        - lambda
      properties:
        uid:
          type: string
          description: function unique identifier
        type: # pass, literal, assignment, condition, decision
          type: string
          description: >
            states the type of function being computed by this function node<br>
            <em>executable only</em>: [ \"PASS\", \"LITERAL\" ]<br>
            <em>executable + instances (wiring)</em>: [ \"ASSIGN\", \"CONDITION\", \"DECISION\" ]
        reference:
          type: string
          description: grounding reference to scientific variable ontology
        lambda:
          type: string
          description: stringified pythonic version of the lambda function code
        # metadata
        metadata:
          description: Metadata associated with \<grfn>.
          type: array
          items:
            $ref: '#/components/schemas/metadata'

    subgraph:
      title: <subgraph>
      description: >
        TODO
      required:
        - basename
        - nodes
      properties:
        namespace:
          type: string
          description: The namespace path of the subgraph
        scope:
          type: string
          description: The scope path of the subgraph
        basename:
          type: string
          description: a reference to the container that shows the original module path, scope path, and container name
        occurrence_num:
          type: string
          description: The subgraph instance tag
        parent:
          type: string
          description: the container uid for the parent container to this container
        type:
          type: string
          description: >
            \"FuncContainer\", \"CondContainer\", \"LoopContainer\"
        exit:
          type: string
          description: a function unique identifier for the lambda function that computes the exit condition
        nodes:
          type: array
          description: array of uids referring to variables and functions in the subgraph
        # metadata
        metadata:
          description: Metadata associated with \<grfn>.
          type: array
          items:
            $ref: '#/components/schemas/metadata'

    ### metadata

    metadata:
      title: <metadata>
      description: >
        Typed metadata consisting of an array of attribute-value pairs.
        \<grfn> is grounded through metadata.
      required:
        - type
        - attributes
      properties:
        type:
          description: Type of metadata.
          type: string
        provenance:
          description: Provenance of metadata.
          $ref: '#/components/schemas/provenance'
        attributes:
          description: Array of \<attribute> attribute-value pairs.
          type: array
          items:
            $ref: '#/components/schemas/attribute'

    provenance:
      title: <provenance>
      description: Provenance of data.
      required:
        - method
        - date_time
      properties:
        method:
          description: >
            The (top-level) inference method (with version) used to derive data.
          type: string
        date_time:
          description: >
            Date and time that current GrFN was generated.
          type: string
          format: date-time
        source:
          description: >
            Array of attributes pairing source type (name) with source identifier (value).
          type: array
          items:
            $ref: '#/components/schemas/attribute'

    attribute:
      title: <attribute>
      description: An attribute-value pair.
      required:
        - name
        - value
      properties:
        name:
          description: The name of the attribute.
          type: string
        value:
          description: The value of the attribute.
          type: string
