openapi: 3.0.0

info:
  title: GrFN JSON Metadata spec
  description: >
    AutoMATES Grounded Function Network (GrFN) JSON Metadata schema specification
  contact:
    name: Clayton T. Morrison
    email: claytonm@arizona.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0

paths: {}

components:

  schemas:

    ### metadata

    metadata:
      title: <metadata>
      description: >
        Typed metadata consisting of an array of attribute-value pairs.
        \<grfn> is grounded through metadata.
      required:
        - type
        - attributes
        - provenance
      properties:
        type:
          description: Type of metadata.
          type: string
        provenance:
          $ref: '#/components/schemas/provenance'
        # attributes:
        #   description: Array of \<attribute> attribute-value pairs.
        #   type: array
        #   items:
        #     $ref: '#/components/schemas/attribute'

    provenance:
      title: <provenance>
      description: Provenance of metadata.
      required:
        - method
        - timestamp
      properties:
        method:
          description: >
            The (top-level) inference method (with version) used to derive data.
          type: string
        timestamp:
          description: >
            Date and time that metadata was generated.
          type: string
          format: date-time
        # sources:
        #   description: >
        #     Array of sources.
        #     (TODO: add additional source types)
        #   type: array
        #   items:
        #     $ref: '#/components/schemas/text_extraction_ref'

    attribute:
      title: <attribute>
      description: An attribute-value pair.
      required:
        - name
        - value
      properties:
        type:
          default: "attribute"
        name:
          description: The name of the attribute.
          type: string
        value:
          description: The value of the attribute.
          type: string

    ### Equation extraction

    equation_extraction:
      title: <equation_extraction>
      description: Representation of equation extraction.
      required:
        - source_type
        - document_reference_uid
        - text_location
      properties:
        source_type:
          type: string
          default: "equation_document_source"
        document_reference_uid:
          description: uid of \<document_reference>
          type: string
        # text_location:
        #   $ref: '#/components/schemas/text_location'
        equation_number:
          description: Number of equation
          type: integer

    ### Text extraction

    text_extraction:
      title: <text_extraction>
      description: Representation of text extraction.
      required:
        - source_type
        - document_reference_uid
        - text_location
      properties:
        source_type:
          type: string
          default: "text_document_source"
        document_reference_uid:
          description: uid of \<document_reference>
          type: string
        # text_location:
        #   $ref: '#/components/schemas/text_location'
        text_spans:
          $ref: '#/components/schemas/text_span_ref'

    # text_location:
    #   title: <text_location>
    #   description: Coordinates of text spans
    #   properties:
    #     spans:
    #       type: array
    #       items:
    #         $ref: '#/components/schemas/text_span_ref'

    text_span_ref:
      title: <text_span_ref>
      description: >
        COSMOS within-document reference coordinates to a span of text.
      required:
        - page
        - block
        - span
      properties:
        page:
          type: integer
        block:
          type: integer
        span:
          $ref: '#/components/schemas/text_span'

    text_span:
      title: <text_span>
      description: Span of text
      required:
        - char_begin
        - char_end
      properties:
        char_begin:
          description: Character coordinate within a text block where span begins
          type: integer
        char_end:
          description: Character coordinate within a text block where span ends
          type: integer

    ### <ANY>.<code_span>

    code_span_reference:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <ANY>.<code_span_reference>
      description: >
        Reference to a source code span (sub-line, line, block).
      required:
        - code_type
        - code_file_reference_uid
      properties:
        type:
          default: "code_span"
        code_type:
          description: >
            The role the the code reference in the span plays.
          type: string
          enum: [ IDENTIFIER, CODE_BLOCK ]
        code_file_reference_uid:
          description: uid for the source code file \<code_file_reference>
          type: string
          format: uuid
        code_span:
          $ref: '#/components/schemas/code_span'

    code_span:
      title: <code_span>
      description: TODO
      required:
        - line_begin
      properties:
        line_begin:
          description: The line number where the identifier name string occurs
          type: integer
        line_end:
          description: The line number where the identifier name string occurs
          type: integer
        col_begin:
          description: The start column of the identifier name string instance
          type: integer
        col_end:
          description: The end column of the identifier name string instance
          type: integer

    ### <grfn>

    grfn_creation:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <grfn>.<creation>
      description: Metadata about the creation of a GrFN JSON file
      required:
        - timestamp
      properties:
        type:
          default: "grfn_creation"
        timestamp:
          description: Creation timestamp
          type: string
          format: datetime

    code_collection_reference:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <grfn>.<code_collection_reference>
      description: Reference to a code collection (i.e., repository)
      required:
        - global_reference_id
        - files
      properties:
        type:
          default: "code_collection_reference"
        global_reference_id:
          description: >
            URL (e.g., GitHub url), or aske_id
          type: string
        files:
          description: TODO
          type: array
          items:
            $ref: '#/components/schemas/code_file_reference'

    code_file_reference:
      title: <code_file_reference>
      description: The reference to a specific file within a code collection
      properties:
        uid:
          description: uid for \<code_file_reference>
          type: string
        name:
          description: File name
          type: string
        path:
          description: Assume starting from root of code collection
          type: string

    textual_document_reference_set:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <grfn>.<textual_document_reference_set>
      description: >
        host: \<grfn> <br>
        A reference to a textual document (e.g., documentation, scientific publication, etc.).
      required:
        - documents
      properties:
        type:
          default: "textual_document_references"
        documents:
          description: List of document references
          type: array
          items:
            $ref: '#/components/schemas/textual_document_reference'

    textual_document_reference:
      title: <textual_document_reference>
      description: Document reference.
      required:
        - uid
        - global_reference_id
      properties:
        uid:
          description: Unique identifier of the \<document_reference>
          type: string
        global_reference_id:
          description: >
            Identifier of source document.<br>
            Rank preference of identifier type:<br>
            (1) DOI (digital object identifier) recognized by COSMOS<br>
            (2) PMID (Pubmed ID) or other DOI<br>
            (3) aske_id (ASKE unique identifier)
          type: string
        cosmos_id:
          description: ID of COSMOS component used to process document.
          type: string
        cosmos_version_number:
          description: Version number of COSMOS component.
          type: string
        automates_id:
          description: ID of AutoMATES component used to process document.
          type: string
        automates_version_number:
          description: Version number of AutoMATES component.
          type: string
        bibjson:
          description: The bibjson entry for this document.<br>
          $ref: '#/components/schemas/bibjson'

    bibjson:
      title: <bibjson>
      description: See http://okfnlabs.org/bibjson/

    ### <function>

    equation_definition:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <function>.<equation_definition>
      description: >
        host: \<function> <br>
        Definition of host derived from an equation source.<br>
        Example: "attributes": { "text_identifier": "Î³", "text_definition": "gamma" }
      required:
        - equation_extraction
        - equation_source
      properties:
        type:
          default: "equation_definition"
        equation_extraction:
          $ref: '#/components/schemas/equation_extraction'
        equation_latex_source:
          description: Source (latex) of equation
          type: string

    ### <variable>

    # variable_code_spans:
    #   allOf:
    #     - $ref: '#/components/schemas/metadata'
    #   title: <variable>.<code_spans>
    #   description: >
    #     host: \<variable> <br>
    #     Array of \<code_span>s for a \<variable> definition.
    #     A \<variable> instance index corresponds to the index in the code_spans array.
    #   required:
    #     - code_file_reference_uid
    #     - code_spans
    #   properties:
    #     type:
    #       default: "equation_parameter"
    #     code_file_reference_uid:
    #       description: uid for the source code file \<code_file_reference>
    #       type: string
    #       format: uuid
    #     code_spans:
    #       description: TODO
    #       type: array
    #       items:
    #         $ref: '#/components/schemas/code_span'

    data_type:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<data_type>
      description: >
        host: \<variable> <br>
        Data type associated with \<variable>.
      required:
        - data_type
      properties:
        type:
          default: "equation_parameter"
        data_type:
          description: >
            Primitive data types:<br>
            <em>Atomic</em>: \"BOOLEAN\", \"INTEGER\", \"FLOAT\", \"STRING\"<br>
            <em>Compound</em>: \"SET\", \"SEQUENCE\", \"DICTIONARY\", \"COMPOSITE\"
          type: string
          enum: [ BOOLEAN, INTEGER, FLOAT, STRING, SET, SEQUENCE, DICTIONARY, COMPOSITE ]

    equation_parameter:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<equation_parameter>
      description: >
        host: \<variable> <br>
        Association of parameter values extracted from equations to host \<variable>.
      required:
        - equation_extraction
        - varaible_identifier
        - value
      properties:
        type:
          default: "equation_parameter"
        equation_extraction:
          $ref: '#/components/schemas/equation_extraction'
        variable_identifier:
          description: Variable identifier in equation
          type: string
        value:
          description: >
            TODO: should this be typed value/object?
          type: string

    text_definition:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<text_definition>
      description: >
        host: \<variable> <br>
        Definition of host derived from a text source.<br>
        Example: "attributes": { "text_identifier": "Î³", "text_definition": "gamma" }
      required:
        - text_extraction
        - variable_identifier
        - variable_definition
      properties:
        type:
          default: "text_definition"
        text_extraction:
          $ref: '#/components/schemas/text_extraction'
        variable_identifier:
          description: Variable identifier
          type: string
        variable_definition:
          description: Variable definition text
          type: string

    # are these test-based, or are they parameter-code-based ?
    text_parameter:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<text_parameter>
      description: >
        host: \<variable> <br>
        Association of parameter values extracted from text to host \<variable>.
      required:
        - text_extraction
        - variable_identifier
        - value
      properties:
        type:
          default: "text_parameter"
        text_extraction:
          $ref: '#/components/schemas/text_extraction'
        variable_identifier:
          description: Variable identifier in text
          type: string
        value:
          description: >
            TODO: should this be typed value/object?
          type: string

    measurement_scale:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<measurement_scale>
      description: >
        host: \<variable> <br>
        The measurement scale of \<variable> value.<br>
      required:
        - measurement_scale
      properties:
        type:
          default: "measurement_scale"
        measurement_scale:
          description: >
            Values: \"binary\", \"categorical\", \"continuous\"
          type: string
          enum: [ BINARY, CATEGORICAL, CONTINUOUS ]

    value_domain:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <variable>.<value_domain>
      description: >
        host: \<variable> <br>
        Expression of the possible values data can take, as interval.<br>
      required:
        - value_domain
      properties:
        type:
          default: "value_domain"
        value_domain:
          description: >
            Example\: \"(and (> v -infty) (< v infty))\"
          type: string

    ### <type>

    type_alias:
      allOf:
        - $ref: '#/components/schemas/metadata'
      title: <type>.<type_alias>
      description: >
        host: \<type>
        Alias name of a \<type>. <br>
        (E.g., using C typedef as alternate alias name to a \<type>).
      required:
        - alias
      properties:
        type:
          default: "type_alias"
        alias:
          description: Alias name
          type: string
