swagger: "2.0"
info:
  description: "This document describes the API for interacting with AutoMATES GrFN."
  version: "1.0.0"
  title: "AutoMATES GrFN"
  termsOfService: ""
  contact:
    email: "claytonm@arizona.edu"
  license:
    name: "TODO Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TODOhost"
basePath: "/v1"
tags:
- name: "generate"
  description: "Calls to interact with GrFN generation"
  # externalDocs:
  #   description: "Find out more"
  #   url: "http://swagger.io"
- name: "execute"
  description: "Calls to execute GrFN models"
  # externalDocs:
  #   description: "Find out more about our store"
  #   url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /generate:
    post:
      tags:
      - "generate"
      summary: "Generate the GrFN json for given source files"
      description: ""
      operationId: "generate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object representing the source code to generate GrFN from"
        required: true
        schema:
          $ref: "#/definitions/Source"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GrFNResult"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiResponse"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
  /execute:
    post:
      tags:
      - "execute"
      summary: "Executes a grfn with given inputs and provides the results."
      description: ""
      operationId: "execute"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Object containing GrFN json and describing inputs for execution"
        required: true
        schema:
          $ref: "#/definitions/Execution"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ExecutionResult"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiResponse"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"
    
definitions:

  Source:
    type: "object"
    properties:
      files:
        type: "array"
        items:
          type: "object"
          properties:
            file_name:
              type: "string"
            file_type: 
              type: "string"
            base64_encoding: 
              type: "string"
      source_language:
        description: "Specifies the source language for all supplied files. Can be"
        type: "string"
        enum:
          - c
          - fortran
          - python
          
  GrFNResult:
    type: "object"
    properties:
      grfn:
        description: "A GrFN object as defined here https://ml4ai.github.io/automates-v2/grfn_v3.0.0.html"
        type: "object"
      inputs:
        type: "array"
        items: 
          type: "object"
          properties:
            variable_name: 
              type: "string"
            variable_type:
              type: "string"
              enum:
                - int
                - float
                - string
                - list
      outputs:
        type: "array"
        items: 
          type: "object"
          properties:
            variable_name: 
              type: "string"
            variable_type:
              type: "string"
              enum:
                - int
                - float
                - string
                - list   
  Execution:
    type: "object"
    properties:
      inputs:
        type: "array"
        items:
          type: "object"
          properties: 
            variable_name: 
              type: "string"
            value: 
              type: "array"
              items:
                type: "string"
      grfn:
        description: "A GrFN object as defined here https://ml4ai.github.io/automates-v2/grfn_v3.0.0.html"
        type: "object"
        
  ExecutionResult:
    type: "object"
    properties:
      outputs:
        type: "array"
        items:
          type: "object"
          properties: 
            variable_name: 
              type: "string"
            results: 
              type: "array"
              items:
                type: "string"
    
  
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        description: "success or describes the encountered error"
        type: "string"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"